### ISSUE TITLE
issue during local deployment (urlparse)

### ISSUE THREAD

**Issue by pdehaye** [OpenHumans/open-humans#709]
When comes the time to run `./manage.py runserver`, I get an error. It looks like it could be related to python3/python differences, because of the requirement for `python3-openid`.

```
(oh_env) pdehaye@PaulOliviersMBP open-humans (master)*$ ./manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x1068c5410>
Traceback (most recent call last):
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/social/apps/django_app/default/models.py", line 9, in <module>
    from social.storage.django_orm import DjangoUserMixin, \
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/social/storage/django_orm.py", line 8, in <module>
    from social.storage.base import UserMixin, AssociationMixin, NonceMixin, \
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/social/storage/base.py", line 12, in <module>
    from openid.association import Association as OpenIdAssociation
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/openid/association.py", line 30, in <module>
    from openid import cryptutil
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/openid/cryptutil.py", line 33, in <module>
    from openid.oidutil import toBase64, fromBase64
  File "/Users/pdehaye/tests/open-humans/oh_env/lib/python2.7/site-packages/openid/oidutil.py", line 17, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse
```

**Comment by beaugunderson** [comment]
i had the same issue:

![screenshot](https://i.imgur.com/REicVZ0.png)

https://github.com/jazzband/pip-tools/issues/575

> Make sure to clear you dependency cache: pip-compile --rebuild

i think that's what fixed it for me

**Comment by gedankenstuecke** [comment]
@pdehaye Was @beaugunderson's comment helpful in resolving this?

**Comment by pdehaye** [comment]
I had missed the comment, and haven't tried since...

**Comment by jhdulaney** [comment]
Seems that this has gone away.
